-- migrate:up
CREATE TABLE owners (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    resolver public.repo_resolver NOT NULL,
    slug public.citext NOT NULL,
    name TEXT,
    description TEXT,
    extra jsonb NOT NULL DEFAULT '{}',
    shards_count INT,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TRIGGER set_timestamp BEFORE UPDATE ON public.owners FOR EACH ROW EXECUTE PROCEDURE public.trigger_set_timestamp();

CREATE UNIQUE INDEX owners_resolver_slug_idx ON public.owners USING btree (resolver, slug);
ALTER TABLE owners
  ADD CONSTRAINT owners_resolver_slug_uniq UNIQUE USING INDEX owners_resolver_slug_idx;

ALTER TABLE repos
  ADD COLUMN owner_id bigint REFERENCES owners(id);

-- migrate:down
ALTER TABLE repos DROP COLUMN owner_id;

DROP TABLE owners;
