language: crystal

addons:
  postgresql: "12"

env:
  TEST_DATABASE_URL: "postgres://postgres:@localhost/shardbox"

services:
- postgresql

before_script:
- crystal --version
- shards --version
- shards check || shards install
- |
  sudo apt update
  sudo apt-get --yes remove postgresql\*
  sudo apt-get install -y postgresql-12 postgresql-client-12
  sudo cp /etc/postgresql/{9.6,12}/main/pg_hba.conf
  sudo service postgresql restart 12
- |
  sudo apt install --yes cmake
  if [ ! -f "~/lib/libgit2" ]; then
    scripts/build_libgit2.sh ~ maint/v0.27
  fi
  export LIBRARY_PATH=$LIBRARY_PATH:~/lib
  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/lib
- make test_db

script:
- crystal spec
- make test/migration
- make bin/worker
- |
  export DATABASE_URL=$TEST_DATABASE_URL
  bin/worker sync_repos && bin/worker update_metrics
- crystal tool format src spec
