dist: bionic
language: crystal

build_addons: &build_addons
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
    - libgit2-dev

crystal:
- latest

cache:
- shards
- directories:
  - vendor/

env:
  global:
    - PGPORT: 5433
    - TEST_DATABASE_URL: "postgres://postgres:@localhost:5433/shardbox"
    - DBMATE: "vendor/bin/dbmate"
    - SHARDS_OPTS: "--ignore-crystal-version"

jobs:
  include:
  - stage: test
    name: unit tests
    services:
    - postgresql
    addons: *build_addons
    before_script: ./.travis/setup-database.sh
    script: make test
  - stage: test
    name: migration test
    addons: *build_addons
    before_script: ./.travis/setup-database.sh
    script: make test_db test/migration
  - stage: test
    name: integration test
    addons: *build_addons
    before_script: ./.travis/setup-database.sh
    script:
    - make test_db bin/worker
    - |
      export DATABASE_URL=$TEST_DATABASE_URL
      bin/worker sync_repos && bin/worker update_metrics
  - stage: test
    name: format
    script: crystal tool format --check src spec
