---
name: Environment Management
shards:
- github: marciogm/asdf-crystal
  description: Plugin for asdf version manager
- github: pine/crenv
  description: Crystal version manager
- github: maiha/rcm.cr
  description: Redis Cluster Manager
